DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Sale;
DROP TABLE IF EXISTS SaleItem;
DROP TABLE IF EXISTS Salesman;

CREATE TABLE Client (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cnpj BIGINT NOT NULL,
  name VARCHAR(250) NOT NULL,
  business_area VARCHAR(250) NOT NULL
);

CREATE TABLE Sale (
  sale_id INT NOT NULL PRIMARY KEY,
  salesman_name VARCHAR(250) NOT NULL
);

CREATE TABLE SaleItem (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  sale_id INT NOT NULL,
  sale_item_id BIGINT NOT NULL,
  quantity BIGINT NOT NULL,
  price DECIMAL(20, 2),
  total_price DECIMAL(20, 2)
);

CREATE TABLE Salesman (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cpf BIGINT NOT NULL,
  name VARCHAR(250) NOT NULL,
  salary DECIMAL(20, 2)
);